// Code generated by MockGen. DO NOT EDIT.
// Source: table.go
//
// Generated by this command:
//
//	mockgen -source=table.go -destination=mocks/databse_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	database "backend/internal/database"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// GetEditionLiveMatches mocks base method.
func (m *MockDatabase) GetEditionLiveMatches(ctx context.Context, competitionID, startYear int) ([]database.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditionLiveMatches", ctx, competitionID, startYear)
	ret0, _ := ret[0].([]database.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditionLiveMatches indicates an expected call of GetEditionLiveMatches.
func (mr *MockDatabaseMockRecorder) GetEditionLiveMatches(ctx, competitionID, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditionLiveMatches", reflect.TypeOf((*MockDatabase)(nil).GetEditionLiveMatches), ctx, competitionID, startYear)
}

// GetEditionResult mocks base method.
func (m *MockDatabase) GetEditionResult(ctx context.Context, competitionID, startYear int) ([]database.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditionResult", ctx, competitionID, startYear)
	ret0, _ := ret[0].([]database.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditionResult indicates an expected call of GetEditionResult.
func (mr *MockDatabaseMockRecorder) GetEditionResult(ctx, competitionID, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditionResult", reflect.TypeOf((*MockDatabase)(nil).GetEditionResult), ctx, competitionID, startYear)
}

// GetEditionUpcommingMatches mocks base method.
func (m *MockDatabase) GetEditionUpcommingMatches(ctx context.Context, competitionID, startYear int) ([]database.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEditionUpcommingMatches", ctx, competitionID, startYear)
	ret0, _ := ret[0].([]database.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEditionUpcommingMatches indicates an expected call of GetEditionUpcommingMatches.
func (mr *MockDatabaseMockRecorder) GetEditionUpcommingMatches(ctx, competitionID, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEditionUpcommingMatches", reflect.TypeOf((*MockDatabase)(nil).GetEditionUpcommingMatches), ctx, competitionID, startYear)
}
