// Code generated by MockGen. DO NOT EDIT.
// Source: sync.go
//
// Generated by this command:
//
//	mockgen -source=sync.go -destination=mocks/sync_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	api "backend/internal/api"
	database "backend/internal/database"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// FetchAreas mocks base method.
func (m *MockAPI) FetchAreas() ([]api.Area, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAreas")
	ret0, _ := ret[0].([]api.Area)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAreas indicates an expected call of FetchAreas.
func (mr *MockAPIMockRecorder) FetchAreas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAreas", reflect.TypeOf((*MockAPI)(nil).FetchAreas))
}

// FetchCompetition mocks base method.
func (m *MockAPI) FetchCompetition(code string) (api.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCompetition", code)
	ret0, _ := ret[0].(api.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCompetition indicates an expected call of FetchCompetition.
func (mr *MockAPIMockRecorder) FetchCompetition(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCompetition", reflect.TypeOf((*MockAPI)(nil).FetchCompetition), code)
}

// FetchCompetitions mocks base method.
func (m *MockAPI) FetchCompetitions() ([]api.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCompetitions")
	ret0, _ := ret[0].([]api.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCompetitions indicates an expected call of FetchCompetitions.
func (mr *MockAPIMockRecorder) FetchCompetitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCompetitions", reflect.TypeOf((*MockAPI)(nil).FetchCompetitions))
}

// FetchEdition mocks base method.
func (m *MockAPI) FetchEdition(code string, startYear int) (api.Edition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEdition", code, startYear)
	ret0, _ := ret[0].(api.Edition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEdition indicates an expected call of FetchEdition.
func (mr *MockAPIMockRecorder) FetchEdition(code, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEdition", reflect.TypeOf((*MockAPI)(nil).FetchEdition), code, startYear)
}

// FetchGoalScorers mocks base method.
func (m *MockAPI) FetchGoalScorers(code string, startYear, limit int) ([]api.GoalScorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGoalScorers", code, startYear, limit)
	ret0, _ := ret[0].([]api.GoalScorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGoalScorers indicates an expected call of FetchGoalScorers.
func (mr *MockAPIMockRecorder) FetchGoalScorers(code, startYear, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGoalScorers", reflect.TypeOf((*MockAPI)(nil).FetchGoalScorers), code, startYear, limit)
}

// FetchMatches mocks base method.
func (m *MockAPI) FetchMatches(code string, startYear int) ([]api.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMatches", code, startYear)
	ret0, _ := ret[0].([]api.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMatches indicates an expected call of FetchMatches.
func (mr *MockAPIMockRecorder) FetchMatches(code, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMatches", reflect.TypeOf((*MockAPI)(nil).FetchMatches), code, startYear)
}

// FetchTeams mocks base method.
func (m *MockAPI) FetchTeams(code string, startYear int) ([]api.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTeams", code, startYear)
	ret0, _ := ret[0].([]api.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTeams indicates an expected call of FetchTeams.
func (mr *MockAPIMockRecorder) FetchTeams(code, startYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTeams", reflect.TypeOf((*MockAPI)(nil).FetchTeams), code, startYear)
}

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// SaveAreas mocks base method.
func (m *MockDatabase) SaveAreas(arg0 []database.Area) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAreas", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAreas indicates an expected call of SaveAreas.
func (mr *MockDatabaseMockRecorder) SaveAreas(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAreas", reflect.TypeOf((*MockDatabase)(nil).SaveAreas), arg0)
}

// SaveCompetitions mocks base method.
func (m *MockDatabase) SaveCompetitions(arg0 []database.Competition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCompetitions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCompetitions indicates an expected call of SaveCompetitions.
func (mr *MockDatabaseMockRecorder) SaveCompetitions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCompetitions", reflect.TypeOf((*MockDatabase)(nil).SaveCompetitions), arg0)
}

// SaveEdition mocks base method.
func (m *MockDatabase) SaveEdition(arg0 database.Edition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEdition", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEdition indicates an expected call of SaveEdition.
func (mr *MockDatabaseMockRecorder) SaveEdition(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEdition", reflect.TypeOf((*MockDatabase)(nil).SaveEdition), arg0)
}

// SaveGoalScorers mocks base method.
func (m *MockDatabase) SaveGoalScorers(arg0 []database.GoalScorer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGoalScorers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGoalScorers indicates an expected call of SaveGoalScorers.
func (mr *MockDatabaseMockRecorder) SaveGoalScorers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGoalScorers", reflect.TypeOf((*MockDatabase)(nil).SaveGoalScorers), arg0)
}

// SaveMatches mocks base method.
func (m *MockDatabase) SaveMatches(arg0 []database.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMatches", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMatches indicates an expected call of SaveMatches.
func (mr *MockDatabaseMockRecorder) SaveMatches(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMatches", reflect.TypeOf((*MockDatabase)(nil).SaveMatches), arg0)
}

// SaveTeams mocks base method.
func (m *MockDatabase) SaveTeams(arg0 []database.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTeams", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTeams indicates an expected call of SaveTeams.
func (mr *MockDatabaseMockRecorder) SaveTeams(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTeams", reflect.TypeOf((*MockDatabase)(nil).SaveTeams), arg0)
}
